### ISSUE TITLE
Install husarnet on wsl2

### ISSUE THREAD

**Issue by Fibo27** [husarnet/husarnet#119]
Hi

1.  I installed Husarnet on WSL2 using Single Command as indicated in https://husarnet.com/docs/platform-linux-install/ 
2. I then tried to join a network using the join code using the instruction under Join a Group in https://husarnet.com/docs/cli-guide/
3. I used sudo in 2 above
4. I get the following message  "ERROR:  Error reading secret file, are you root/administrator? open /var/lib/husarnet/daemon_api_token: no such file or directory"

Is there a specific way to join WSL2?

Thanks

**Comment by Fibo27** [comment]
Hi by allowing systemd, the above issue was resolved. I now have the following set-up.
1) Robot: Ubuntu 20.04, installed husarnet. 
2) WSL2: Ubuntu 22.04, installed husarnet
I can ping the above two using the ipv6 address. I can also access the robot remotely from WSL2 using ssh after generating keys using ssh-keygen command.

Also, I am managing the elements of the network using the web console. 

3) I have now also installed husarnet on my windows OS (it is Windows 11, Professional 64 bit system)
Now when i try to add another element using the web console and use the join code directly using the windows CLI, I get the below message
"Error: response status: invalid, error: invalid control secret"

Essentially I am trying to connect my Windows Terminal, the WSL2 Terminal (both using the same hardware) and my Robot (different hardware) on the same network and currently I am not able to initiate husarnet VPN for my Windows terminal. 
Appreciate your feedback.

**Comment by KonradPR** [comment]
Hello,
we have managed to reproduce this error on a similar setup to the one you have described and are currently working on identifying the root cause of it.
We will get back to you as soon as we make progress on this front.

Best regards,
Konrad

**Comment by KonradPR** [comment]
Hello,
we have inspected the issue in detail and we believe that the problem you are experiencing stems form how WSL and Windows on the whole handle binding and networking when both WSL and host system are binding on the same ports.
Best solution for this problem as of right now would be to reconfigure the WSL husarnet daemon service to add an environmental variable that will force daemon to bind on non default port.
Please edit your husarnet.service config file by adding following line in the [service] section (the 6666 port is an example one and you can use whatever suits you but refrain from using the default port number):
Environment=HUSARNET_DAEMON_API_PORT=6666
after this the file should look similar to this:
```
[Unit]
Description=Husarnet
After=network-online.target
Wants=network-online.target

[Service]
Type=notify
ExecStart=/usr/bin/husarnet-daemon
Restart=always
RestartSec=3
NotifyAccess=all
Environment=HUSARNET_DAEMON_API_PORT=6666
[Install]
WantedBy=multi-user.target
```

after this restart the WSL husarnet daemon service and the restart the WIndows husarnet service.

now you should be able to use the windows installation without issue.
However whe using the WSL installation you now will need to add additional parameter to husarnet CLI calls which will indicated the new custom port number on which the daemon is listening as such:
husarnet -p 6666 status

This way you should be able to use both the WSL and the Windows installation of husarnet.
Please let us know if you encounter any issues.

**Comment by Fibo27** [comment]
Hi - thanks - can you please tell me the location of the husarnet.service config file - i tried to look under /var/lib - but the husarnet folder here comes up as permission denied - do i need to chmod?

**Comment by Fibo27** [comment]
Hi thanks - this works! Perhaps you should mention that the husarnet.service config file is in the directory /etc/systemd/system/multi-user.target.wants  

Thanks Again!
