### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by seifEddy** [husarnet/husarnet#123]
**Describe the bug**
I am always getting a TIMEOUT error after trying to communicate with husarnet daemon

**To Reproduce**
$ sudo husarnet join $JOIN_CODE seghiri
 INFO:  Daemon does not seem to be running

Do you want to restart Husarnet Daemon now? [y/N]: Yes

▀  Waiting until we can communicate with husarnet daemon… (7.221s)

**Expected behavior**
I expect to join the network as before since I was always able to join it.
**Screenshots**

**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04.1 LTS
 - Husarnet Version v2.0.141
 - Browser chrome
 - ROS Version ROS-Melodic

**Comment by KonradPR** [comment]
Hi,
In order for us to determine the source of this problem we would need to see the Husarnet logs (output  of `journalctl --unit husarnet`)
If this logs is long in your case you can trim it to the last 100 lines or so as that should be sufficient.
When we get the logs we will try to identify and address the issue as soon as possible.

Best regards,
Konrad

**Comment by seifEddy** [comment]
I do not know if this helps but here is what I got 
`May 13 21:56:14 seghiri systemd[1]: Started Husarnet Daemon.
May 13 21:56:14 seghiri husarnet[27797]: NAME:
May 13 21:56:14 seghiri husarnet[27797]:    Husarnet CLI daemon - Control the local daemon
May 13 21:56:14 seghiri husarnet[27797]: USAGE:
May 13 21:56:14 seghiri husarnet[27797]:    Husarnet CLI daemon command [command options] [arguments...]
May 13 21:56:14 seghiri husarnet[27797]: COMMANDS:
May 13 21:56:14 seghiri husarnet[27797]:    status                          Display current connectivity status
May 13 21:56:14 seghiri husarnet[27797]:    join                            Connect to Husarnet group with given join code and with specified hostname
May 13 21:56:14 seghiri husarnet[27797]:    logs                            Display and manage logs settings
May 13 21:56:14 seghiri husarnet[27797]:    notifications                   Manage notifications on the device.
May 13 21:56:14 seghiri husarnet[27797]:    wait                            Wait until certain events occur. If no events provided will wait for as many elements as it 
May 13 21:56:14 seghiri husarnet[27797]:    start, up                       start husarnet daemon
May 13 21:56:14 seghiri husarnet[27797]:    stop, down                      stop husarnet daemon
May 13 21:56:14 seghiri husarnet[27797]:    restart, down                   restart husarnet daemon
May 13 21:56:14 seghiri husarnet[27797]:    setup-server, change-dashboard  Connect your Husarnet device to different Husarnet infrastructure
May 13 21:56:14 seghiri husarnet[27797]:    whitelist                       Manage whitelist on the device.
May 13 21:56:14 seghiri husarnet[27797]:    hooks                           Manage hooks on the device.
May 13 21:56:14 seghiri husarnet[27797]:    genid, genID, genId, gen-id     Generate a valid identity file
May 13 21:56:14 seghiri husarnet[27797]:    service-install                 install service definition in OS's service manager (e.g. systemctl on Linux)
May 13 21:56:14 seghiri husarnet[27797]:    service-uninstall               remove service definition from OS's service manager (e.g. systemctl on Linux)
May 13 21:56:14 seghiri husarnet[27797]:    help, h                         Shows a list of commands or help for one command
May 13 21:56:14 seghiri husarnet[27797]: OPTIONS:
May 13 21:56:14 seghiri husarnet[27797]:    --help, -h  show help (default: false)
May 13 21:56:14 seghiri husarnet[27797]:    
lines 438-481/481 (END)
`

**Comment by pidpawel** [comment]
This does seem like your installation tries to use CLI binary instead of a daemon binary. Please make sure that systemd is trying to run `husarnet-daemon` and **not** `husarnet` (this is important if you've installed the binaries manually. Any other installation method should handle this automatically.)
You can try using methods described here https://husarnet.com/docs/platform-linux-install/

**Comment by seifEddy** [comment]
Thank you so much,
I changed this:

[Unit]
Description=Husarnet Daemon

[Service]
Type=simple
ExecStart=/usr/bin/**husarnet daemon**

[Install]
WantedBy=multi-user.target

into this:
[Unit]
Description=Husarnet Daemon

[Service]
Type=simple
ExecStart=/usr/bin/**husarnet-daemon**

[Install]
WantedBy=multi-user.target

and it worked.
You saved me thank you so much
