### ISSUE TITLE
[BUG] Husarnet forces lowercase hostnames, preventing connections between machines.

### ISSUE THREAD

**Issue by airfield20** [husarnet/husarnet#124]
**Describe the bug**
husarnet sets hostnames in /etc/hosts files but sets all hostanames to lowercase. i.e. A hostname of Laptop1 will become laptop1. This name mismatch prevents connections from being established.

**To Reproduce**
Install husarnet on 2 machines with uppercase values in their hostnames. You will not be able to establish a connection between them using the hostname.

**Expected behavior**
The /etc/hosts file should contain the actual hostname that the device has. Setting it to a lowercase name may require significant efforts for users.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Husarnet Version 2.0.78
 - ROS Version ROS 1 Noetic

**Comment by ympek** [comment]
Hello @airfield20 

Thank you for the report.

Hostnames on Linux are case-insensitive (try `ping LoCaLhOsT`). As per man hostname(7):

> If a case-insensitive match is found
   between the hostname to be resolved and the first field of a line
       in the file, the substituted name is looked up with no further
       processing.

In fact, we tried to reproduce your issue and the problem looks somewhat different:

![image](https://github.com/husarnet/husarnet/assets/24464784/2f1d0048-fcc5-4613-ba58-6b5f1d28b960)

The entry is added two times, in original and lowercase version. While this is definitely a bug we take note of, it does not prevent the connection as can be seen on the screenshots.

Given all that information, I suspect your connection problem is unrelated to `/etc/hosts` handling. 
Please share your setup (`/etc/hosts` contents, `husarnet status` output and maybe also logs from `journalctl -u husarnet` on both machines). You can drop an email on support@husarnet.com if you do not want to share here.

I'm leaving the issue open for now as it is unclear.

Best regards,
Szymon, Husarnet team.

**Comment by airfield20** [comment]
Hmm if this isnt the issue then Ill have to investigate further why the connections are dropping. I will provide the status and logs soon.

**Comment by airfield20** [comment]
This can be closed, my network environment changed such that only the TCP base server connection is permitted and the connection has stopped dropping since then.
