### ISSUE TITLE
[BUG] syslog being spammed with NAT_INIT_TRANSIENT transient error

### ISSUE THREAD

**Issue by msmcconnell** [husarnet/husarnet#135]
**Describe the bug**
The syslog on Ubuntu 20.04 seems to be getting spammed with the error 
```
tried to serialize unexpected peer to base message type: NAT_INIT_TRANSIENT
```

See a snippet below

```
Oct 26 21:45:24 my_hostname husarnet-daemon[1158]: 2023-10-26_21:45:24 INFO     reestablish connection to [<my ip v6> ]
Oct 26 21:45:27 my_hostname husarnet-daemon[1158]: 2023-10-26_21:45:27 ERROR    tried to serialize unexpected peer to base message type: NAT_INIT_TRANSIENT
Oct 26 21:45:30 my_hostname husarnet-daemon[1158]: 2023-10-26_21:45:30 ERROR    tried to serialize unexpected peer to base message type: NAT_INIT_TRANSIENT
Oct 26 21:45:34 my_hostname husarnet-daemon[1158]: 2023-10-26_21:45:34 ERROR    tried to serialize unexpected peer to base message type: NAT_INIT_TRANSIENT
Oct 26 21:45:37 my_hostname husarnet-daemon[1158]: 2023-10-26_21:45:37 ERROR    tried to serialize unexpected peer to base message type: NAT_INIT_TRANSIENT
Oct 26 21:45:39 my_hostname husarnet-daemon[1158]: 2023-10-26_21:45:39 INFO     received multicast from <a different ip v6>
Oct 26 21:45:40 my_hostname husarnet-daemon[1158]: 2023-10-26_21:45:40 ERROR    tried to serialize unexpected peer to base message type: NAT_INIT_TRANSIENT
Oct 26 21:45:44 my_hostname husarnet-daemon[1158]: 2023-10-26_21:45:44 ERROR    tried to serialize unexpected peer to base message type: NAT_INIT_TRANSIENT
Oct 26 21:45:47 my_hostname husarnet-daemon[1158]: 2023-10-26_21:45:47 ERROR    tried to serialize unexpected peer to base message type: NAT_INIT_TRANSIENT
```

This appears repeatedly in the log. 

**To Reproduce**
Not sure how repeatable it is, but this is my setup. 

Device with log
Device: Nvidia Orin NX
OS: Ubuntu 20.04.6 LTS
Kernel: Linux 5.10.104
Architecture: arm64

Device connected via SSH to Orin NX
Device: Dell Precision 7520 Laptop
OS: Windows 10 Pro 64-bit Version: 22H2 Build: 19045.3570
Architecture: amd64

I've got 5 SSH connections open including a VS Code remote development session all from the windows machine to the linux machine. 

**Expected behavior**
Not getting a constant error in the logs

**Screenshots**

**Desktop (please complete the following information):**

 - OS: See above
 - Husarnet Version: 2.0.170
 - Browser Google Chrome (but not actively used in this scenario)
 - ROS Version ROS-Noetic (but not actively used in this scenario)

**Additional context**

```
:~$ husarnet status
Version
● CLI:                       2.0.170
● Daemon (running):          2.0.170
● Daemon (binary):           2.0.170

Daemon hooks are currently disabled
Dashboard URL
● CLI:                       app.husarnet.com
● Daemon:                    app.husarnet.com

Connection status
● Base Server:               188.165.23.196:443 (TCP)
● TCP is a fallback connection method. You'll get better results on UDP

Readiness
● Is ready to handle data?   yes
● Is ready to join?          yes
● Is joined?                 yes
```

**Comment by pidpawel** [comment]
Hi! I believe this was fixed in version 2.0.180. Could you please test that one too?

**Comment by msmcconnell** [comment]
It does look like that fixed it. Though now there is a lot of 
```
Oct 27 13:54:57 my_hostname husarnet-daemon[66376]: 2023-10-27_13:54:57 INFO     reestablish connection to [<a device ip>]
```

**Comment by fwlodarczyk** [comment]
> It does look like that fixed it. Though now there is a lot of
> 
> ```
> Oct 27 13:54:57 my_hostname husarnet-daemon[66376]: 2023-10-27_13:54:57 INFO     reestablish connection to [<a device ip>]
> ```

Hi

If you are having packet loss, or similar issues make sure you have stable internet connection also please check whitelist.
If things are working as expected just ignore these messages.

Regards, Filip

**Comment by msmcconnell** [comment]
I'm not seeing packet loss when using ping, so I'm not sure why the connection needs to reset so often, but it's not causing issues.  So I guess I'll close this issue.
