### ISSUE TITLE
[BUG] Homebrew on macos with intel cpu: Bad CPU type in executable

### ISSUE THREAD

**Issue by randall05** [husarnet/husarnet#138]
**Describe the bug**
According to the official instructions, i installed the MacOS client by homebrew.
my Macbook is very old:
OS: MacOS 12.7.1
CPU: 2.7 GHz Dual-Core Intel Core i5

the version brew installed on my macbook is: husarnet-macos-2.0.214-arm64.tar.gz

**Comment by ympek** [comment]
Hello @randall05 

Sorry, we only have Apple Silicon/ARM binaries in available in homebrew.
We have untested version of the Intel Mac binary in nightly channel: https://nightly.husarnet.com/
The file is `husarnet-macos-2.0.214-amd64.tar.gz`
You can check it out.
Inside the tar.gz archive you will find two binaries: the daemon binary `husarnet-daemon` which has to be running all the time, along with `husarnet` binary which is the CLI.

Best regards,
ympek

**Comment by randall05** [comment]
oK, i will try it out :)

**Comment by fwlodarczyk** [comment]
@randall05 We are closing the issue, because it looks your problem has been solved.

Feel free to reply if it isn't.
