### ISSUE TITLE
[BUG] Deprecated setting suggested in the "Using Husarnet & ROS 2" tutorial

### ISSUE THREAD

**Issue by nilsjor** [husarnet/husarnet#146]
The [DDS tutorial](https://husarnet.com/docs/tutorial-ros2#using-cyclone-dds) recommends a cyclone xml field that is giving a deprecated warning.

**To Reproduce**
Complete the configuration for Cyclone on the most recent version of cyclone-rmw for ros

**Solution**
the offending field is
```xml
<General>
            <NetworkInterfaceAddress>hnet0</NetworkInterfaceAddress>
```

The newer, recommended settings should be 
```xml
<General>
    <Interfaces>
        <NetworkInterface name="hnet0"/>
    </Interfaces>
```
as presented here: https://cyclonedds.io/docs/cyclonedds/latest/config/network_interfaces.html

Changing this works consistently and eliminates the warning. Tested using ros-humble-rmw-cyclonedds-cpp/jammy,now 1.3.4-1jammy.20240517.155556

**Comment by DominikN** [comment]
Hi, we have updated the ROS 2 tutorial in our docs: https://husarnet.com/docs/tutorial-ros2/

Now there are more setups described, including a custom XML file for CycloneDDS that you need. You are right, there was an old format of the XML file before (now there are both old a new).

**Comment by nilsjor** [comment]
Looks fine! Nice work
