### ISSUE TITLE
[Feature Request] Trigger an optional executable when hosts join or leave a Husarnet network (Husarnet & ROS2)-related

### ISSUE THREAD

**Issue by rubenanapu** [husarnet/husarnet#27]
This is a feature request, rather than an issue.

It would be really awesome if we could have a script executed each time a device joins or leaves a Husarnet network that the current device is added to.

What do we need this?

I was following the [ROS2 + Husarnet tutorial](https://husarnet.com/docs/tutorial-ros2/) and saw that manually modifying the `cyclonedds.xml` and/or `fastdds_husarnet.xml` files each time a device joins the network is really "bad".

If we could have a script called each time a device joins or leaves, updating these **xml** files would be much easier.

The scripts could be called like this:
```
  /path/to/script.sh joined DEVICE_NAME PUBLIC_IPV6
and
 /path/to/script.sh left DEVICE NAME PUBLIC_IPV6
```

And we could set/unset the script using a set-trigger command like this:
```
husarnet add-trigger /path/to/script.sh
husarnet del-trigger /path/to/script.sh
```

Husarnet could check if the file is executable when add-trigger is called, just to avoid problems when trying to execute it.

Or much better yet, **Husarnet could (I ask, if possible) automatically generate/update these `cyclonedds.xml / fastdds_husarnet.xml` somewhere, like /var/lib/husarnet/**, for example.

For the moment, while we still don't have this feature, I'll try to be monitoring `/etc/hosts`, but having this trigger feature would be really great.

Thanks in advance to anyone who implements this.

**Comment by DominikN** [comment]
Hi @rubenanapu, in my latest blog post I present a setup where you do not need to modify DDS XML config file while adding (or removing) devices to ROS 2 network: https://husarnet.com/blog/ros2-dds-discovery-server

Please check it out and let me know whether something like that works for you.

**Comment by rubenanapu** [comment]
Hi @DominikN ,

I still couldn't test what you proposed in the link above, but I'll give it a try as soon as I can.

Thanks for the post.

**Comment by pidpawel** [comment]
We've implemented hooks mechanism if you want to trigger your own executables.
Tutorial is here at the moment, but it may be moved in the future so search for hooks https://husarnet.com/docs/tutorial-hooks/
Feel free to reopen if you have any additional questions.

**Comment by rubenanapu** [comment]
I just tested the hooks, and it works.

Thank you very much for implementing this, @pidpawel.

In conjunction with [husarnet-dds](https://github.com/husarnet/husarnet-dds), these hooks help a lot.
