### ISSUE TITLE
create account has failed

### ISSUE THREAD

**Issue by cafuc1234** [husarnet/husarnet#41]
When I register my account, enter my email address and password, click Register, and the result will return 500

**Comment by KonradPR** [comment]
Hi,

if I understand correctyl the problem manifests when You try to log in after registering, is that right?

Best regards,
Konrad

**Comment by cafuc1234** [comment]
> Hi,
> 
> if I understand correctly the problem manifests when You try to log in after registering, is that right?
> Please make sure that You have activated Your account by clicking the link in the activation email.
> 
> Best regards,
> Konrad

Your understanding is wrong. My problem is that when I register a new account, I input the email address and password, and then click Register to return 500 errors.

**Comment by KonradPR** [comment]
Are You sure that You have not made an account with the same email address in the past?
I suggest trying the password change option under the forgotten password link. This should let You change password 
to the account connected with the aforementioned email address. 
If You are sure that there was no previous account registered with that address please contact us providing the email address in question so we can investigate further.

Best regards,
Konrad

**Comment by cafuc1234** [comment]
I tried to enter my email address and click forget password, but it prompted me that I didn't register, so I thought the server might be down




---Original---
From: ***@***.***&gt;
Date: Mon, Jun 6, 2022 08:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [husarnet/husarnet] create account has failed (Issue #41)




 
Are You sure that You have not made an account with the same email address in the past?
 I suggest trying the password change option under the forgotten password link. This should let You change password
 to the account connected with the aforementioned email address.
 If You are sure that there was no previous account registered with that address please contact us providing the email address in question so we can investigate further.
 
Best regards,
 Konrad

**Comment by cafuc1234** [comment]
> Are You sure that You have not made an account with the same email address in the past?
> I suggest trying the password change option under the forgotten password link. This should let You change password 
> to the account connected with the aforementioned email address. 
> If You are sure that there was no previous account registered with that address please contact us providing the email address in question so we can investigate further.
> 
> Best regards,
> Konrad 
> 

I tried to enter my email address and click forget password, but it prompted me that I didn't register, so I thought the server might be down

**Comment by KonradPR** [comment]
Sorry for taking a longer time to reply, but I was trying to investigate the problem You described further.
Unfortunately, I was not able to reproduce a similar error in a way other than trying to register an account using email I already used. Our servers have not encountered any problems in recent time so that should not be the cause.
If You could provide any more details about the problem that may help us solve it.

Best regards,
Konrad

**Comment by KonradPR** [comment]
I am now closing this issue as stale since no further information was provided and as such we are unable to properly investigate the problem.
If You still want help solving this issue feel free to reopen it, providing additional information.

Best regards,
Konrad

**Comment by fd3s1** [comment]
I have the same problem now

**Comment by fd3s1** [comment]
![image](https://user-images.githubusercontent.com/75970806/181878406-b20f2fc4-3173-4b7c-828a-2edc00d44883.png)

**Comment by cafuc1234** [comment]
I tried to enter my email address and click forget password, but it prompted me that I didn't register, so I thought the server might be down




---Original---
From: ***@***.***&gt;
Date: Mon, Jun 6, 2022 08:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [husarnet/husarnet] create account has failed (Issue #41)




 
Are You sure that You have not made an account with the same email address in the past?
 I suggest trying the password change option under the forgotten password link. This should let You change password
 to the account connected with the aforementioned email address.
 If You are sure that there was no previous account registered with that address please contact us providing the email address in question so we can investigate further.
 
Best regards,
 Konrad
